name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            # Clean up old backend container
            docker stop my-strapi-container || true
            docker rm my-strapi-container || true

            # Pull and run backend Docker container
            docker pull shivagyawali/guru-kirpa-be:latest
            docker run -d --name my-strapi-container -p 1337:1337 shivagyawali/guru-kirpa-be:latest

  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            # Clean up old frontend container
            docker stop my-guru-kripa-fe-container || true
            docker rm my-guru-kripa-fe-container || true

            # Pull and run frontend Docker container 
            docker pull shivagyawali/guru-kirpa-fe:latest
            docker run -d --name my-guru-kripa-fe-container -p 8081:80 shivagyawali/guru-kirpa-fe:latest

            # Copy necessary files from backend container
            docker cp my-strapi-container:/var/www/gurukripanepal /var/www/
