name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            echo "Stopping anything on port 1337..."
            docker ps -q --filter "publish=1337" | xargs -r docker stop
            docker ps -q --filter "publish=1337" | xargs -r docker rm

            echo "Cleaning old backend container..."
            docker stop my-strapi-container || true
            docker rm my-strapi-container || true

            echo "Pulling new backend image..."
            docker pull shivagyawali/guru-kirpa-be:latest

            echo "Starting backend container..."
            docker run -d --name my-strapi-container -p 1337:1337 shivagyawali/guru-kirpa-be:latest

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Deploy Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            echo "Stopping old frontend container..."
            docker stop my-guru-kripa-fe-container || true
            docker rm my-guru-kripa-fe-container || true

            echo "Pulling new frontend image..."
            docker pull shivagyawali/guru-kirpa-fe:latest

            echo "Starting frontend container..."
            docker run -d --name my-guru-kripa-fe-container -p 8081:80 shivagyawali/guru-kirpa-fe:latest

            echo "Copying required files from backend container..."
            docker cp my-strapi-container:/var/www/gurukripanepal /var/www/
